services:

  # Console commands
  paveldanilin\RequestBodyBundle\Command\ShowUsageCommand:
    public: true
    calls:
      - setScanDir: [ '%kernel.project_dir%/src' ]
      - setAnnotationScanner: [ '@annotation_scanner' ]
    tags:
      - { name: 'console.command', command: 'rb:show' }

  # Common services
  annotation_scanner:
    class: paveldanilin\RequestBodyBundle\Service\AnnotationScanner
    arguments: ['@annotations.reader']

  request_body_service:
    class: paveldanilin\RequestBodyBundle\Service\RequestBodyService
    arguments: ['@annotations.reader', '@serializer', '@validator']

  paveldanilin\RequestBodyBundle\EventListener\RequestBodyListener:
    arguments: ['@request_body_service']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, priority: 240 }

  paveldanilin\RequestBodyBundle\ArgumentResolver\RequestBodyResolver:
    arguments: ['@request_body_service']
    tags:
      - { name: controller.argument_value_resolver, priority: 240 }
